#ifndef MONSTER_H
#define MONSTER_H

#include <Eigen/Core>
#include <vector>
#include <igl/delaunay_triangulation.h>
#define ANSI_DECLARATORS
#define TRILIBRARY
#include <igl/triangle/triangulate.h>
#include <QImage>
#include <QPainter>
#include <QPainterPath>

struct Stroke {
    std::vector<Eigen::Vector2f> points;
    // True if this stroke is generated by the system to close an open stroke.
    bool isClosingCurve = false;
    // True if this closing curve acts as a shared interface between two regions.
    // This should only ever be true when isClosingCurve is also true.
    bool isMergingBoundary = false;
    // Depth is assigned when a stroke is committed:
    // if it does not intersect any previous stroke, depthOrder is 0;
    // otherwise it is max(intersecting previous strokes' depthOrder) + 1.
    int depthOrder = 0;

    bool isClosed(float eps = 1e-3f) const {
        if (points.size() < 3) {
            return false;
        }

        const Eigen::Vector2f delta = points.front() - points.back();
        return delta.squaredNorm() <= eps * eps;
    }
};

struct Region {
    std::vector<Stroke> boundaries; 
    // closing curves only stores in boundaries

    // Regions inherit the depthOrder of their open stroke boundary.
    int depthOrder = 0;
};

struct MeshPart {
    Eigen::MatrixXd V;        // stitched front+back vertices
    Eigen::MatrixXi F;        // stitched front+back faces
    Eigen::VectorXi sideFlags;
    std::vector<bool> isDirichlet; // on Dp: h=0 in Poisson solve
    std::vector<bool> isMerging;      // on Bp: candidate for welding
    std::vector<std::pair<int,int>> armpitPairs;
    int depthOrder;
};

struct StitchedMesh {
    Eigen::MatrixXd V;
    Eigen::MatrixXi F;
    Eigen::VectorXi sideFlags;
    std::vector<bool> isDirichlet;
    std::vector<bool> isMerging;
    std::vector<std::pair<int,int>> armpitPairs; // front/back index pairs at Bp endpoints
};

class monster {
public:
    monster();
    StitchedMesh buildMesh(const std::vector<Region>& regions,
                           const std::vector<std::vector<int>>& connectedRegions,
                           int canvasWidth, int canvasHeight);

    QImage renderRegionToMask(const Region& region, int width, int height);
    std::vector<Eigen::Vector2f> traceBoundary(const QImage& mask);
    std::vector<Eigen::Vector2f> findBpPixels(const QImage& hostMask,
                                              const QImage& attachmentMask);
    StitchedMesh stitchParts();
    std::vector<MeshPart> m_meshParts;
    std::vector<bool> buildIsMerging(const Eigen::MatrixXd& V,
                                     const std::vector<Eigen::Vector2f>& bpPoints,
                                     double eps = 0.5f);

private:
    // Step 1: Triangulate a region's 2D boundary using CDT
    void triangulateRegion(const Region& region, Eigen::MatrixXd& V, int& n,
                           Eigen::MatrixXd& V2, Eigen::MatrixXi& F2,
                           const std::vector<Eigen::Vector2f>& extraPoints = {});

    // Step 2: Duplicate front/back of mesh
    MeshPart createFrontBack(const Eigen::MatrixXd& V2, const Eigen::MatrixXi& F2,
                             const std::vector<bool>& isDirichletIn,
                             int depthOrder,
                             const std::vector<bool>& isMergingIn);

    // Step 3: Split host mesh along Bp to create a hole for the attachment
    std::vector<int> splitAlongBp(Eigen::MatrixXd& V2, Eigen::MatrixXi& F2,
                      const std::vector<Eigen::Vector2f>& bpPoints);

    // Step 4: Get merging boundary points from a region
    std::vector<Eigen::Vector2f> getMergingBoundaryPoints(const Region& region);

    void weldSeams(StitchedMesh& mesh);

    std::vector<bool> buildIsDirichlet(const Eigen::MatrixXd& V2,
                                       const Eigen::MatrixXd& V_input,
                                       int n, double eps = 0.5);
};


#endif // MONSTER_H
