#ifndef MONSTER_H
#define MONSTER_H

#include <Eigen/Core>
#include <vector>
#include <igl/delaunay_triangulation.h>
#define ANSI_DECLARATORS
#define TRILIBRARY
#include <igl/triangle/triangulate.h>

struct Stroke {
    std::vector<Eigen::Vector2f> points;
    // True if this stroke is generated by the system to close an open stroke.
    bool isClosingCurve = false;
    // True if this closing curve acts as a shared interface between two regions.
    // This should only ever be true when isClosingCurve is also true.
    bool isMergingBoundary = false;
    // Depth is assigned when a stroke is committed:
    // if it does not intersect any previous stroke, depthOrder is 0;
    // otherwise it is max(intersecting previous strokes' depthOrder) + 1.
    int depthOrder = 0;

    bool isClosed(float eps = 1e-3f) const {
        if (points.size() < 3) {
            return false;
        }

        const Eigen::Vector2f delta = points.front() - points.back();
        return delta.squaredNorm() <= eps * eps;
    }
};

struct Region {
    std::vector<Stroke> boundaries; 
    // closing curves only stores in boundaries

    // Regions inherit the depthOrder of their open stroke boundary.
    int depthOrder = 0;
};

struct MeshPart {
    Eigen::MatrixXd V;        // stitched front+back vertices
    Eigen::MatrixXi F;        // stitched front+back faces
    Eigen::VectorXi sideFlags;
    std::vector<bool> isDirichlet;
    int depthOrder;
};

struct StitchedMesh {
    Eigen::MatrixXd V; // Nx2 matrix, each row is a vertex [x, y]
    Eigen::MatrixXi F; // Nx3 matrix, each row is a triangle [i, j, k]
    Eigen::VectorXi sideFlags; // Nx1, +1 for front-facing, -1 for back-facing
    std::vector<bool> dirichlet; // Nx1, true if vertex is on drawn boundary Dp (h=0)
};

class monster {
public:
    monster();
    Region makeTestBody();
    Region makeTestLeg();
    StitchedMesh buildMesh(const std::vector<Region>& regions);
    StitchedMesh stitchParts();
    std::vector<MeshPart> m_meshParts;

private:
    // Step 1: Triangulate a region's 2D boundary using CDT
    void triangulateRegion(const Region& region, Eigen::MatrixXd& V, int& n,
                           Eigen::MatrixXd& V2, Eigen::MatrixXi& F2,
                           const std::vector<Eigen::Vector2f>& extraPoints = {});

    // Step 2: Duplicate front/back and stitch along Dp
    MeshPart stitchFrontBack(const Eigen::MatrixXd& V2, const Eigen::MatrixXi& F2,
                             int n, int depthOrder);

    // Step 3: Split host mesh along Bp to create a hole for the attachment
    std::vector<int> splitAlongBp(Eigen::MatrixXd& V2, Eigen::MatrixXi& F2,
                                  const std::vector<Eigen::Vector2f>& bpPoints);

    // Step 4: Get merging boundary points from a region
    std::vector<Eigen::Vector2f> getMergingBoundaryPoints(const Region& region);

    MeshPart stitchAttachmentToHost(MeshPart& host, MeshPart& attachment,
                                    const std::vector<int>& hostSplitIndices,
                                    const std::vector<Eigen::Vector2f>& bpPoints);
};


#endif // MONSTER_H
