#ifndef MONSTER_H
#define MONSTER_H

#include <Eigen/Core>
#include <vector>
#include <igl/delaunay_triangulation.h>
#define ANSI_DECLARATORS
#define TRILIBRARY
#include <igl/triangle/triangulate.h>

struct Stroke {
    std::vector<Eigen::Vector2f> points;
    // True if this stroke is generated by the system to close an open stroke.
    bool isClosingCurve = false;
    // True if this stroke acts as a shared interface between two regions.
    bool isMergingBoundary = false;
    // Depth is assigned when a stroke is committed:
    // if it does not intersect any previous stroke, depthOrder is 0;
    // otherwise it is max(intersecting previous strokes' depthOrder) + 1.
    int depthOrder = 0;

    bool isClosed(float eps = 1e-3f) const {
        if (points.size() < 3) {
            return false;
        }

        const Eigen::Vector2f delta = points.front() - points.back();
        return delta.squaredNorm() <= eps * eps;
    }
};

struct Region {
    std::vector<Stroke> boundaries; 
    // closing curves only stores in boundaries

    // Regions inherit the depthOrder of their open stroke boundary.
    int depthOrder = 0;
};

struct MeshPart { // internal to monster.cpp
    Eigen::MatrixXd V;   // vertices
    Eigen::MatrixXi F;   // triangles
    int side;            // +1 front, -1 back
    int depthOrder;
    std::vector<bool> isDirichlet;
};

struct StitchedMesh {
    Eigen::MatrixXd V; // Nx2 matrix, each row is a vertex [x, y]
    Eigen::MatrixXi F; // Nx3 matrix, each row is a triangle [i, j, k]
    Eigen::VectorXi sideFlags; // Nx1, +1 for front-facing, -1 for back-facing
    std::vector<bool> dirichlet; // Nx1, true if vertex is on drawn boundary Dp (h=0)
};

class monster {
public:
    monster();
    Region makeTestBody();
    Region makeTestLeg();
    StitchedMesh buildMesh(const std::vector<Region>& regions);
    std::vector<MeshPart> m_meshParts;
};


#endif // MONSTER_H
